### ISSUE TITLE
imeta mod does not work in 4.2.1 and 4.2.2

### ISSUE THREAD

**Issue by chStaiger** [irods/irods_client_icommands#36] opened 2018-04-10 09:38 UTC
`imeta mod` throws error when modifying metadata (icommands v 4.2.1 or 4.2.2):

```
imeta mod -d test.txt KEY value v:myValue
remote addresses: irods-server ERROR: rcModAVUMetadata failed with error -816000 CAT_INVALID_ARGUMENT
```
while with icommands v 4.1.10 and higher the command works as expected.

**Comment by trel** [comment] 2018-04-10 10:49
Thank you!   This appears to be a duplicate of https://github.com/irods/irods/issues/3787

**Closed by trel** 2018-04-10 10:49 UTC
