### ISSUE TITLE
irods-icommands installs without irods-runtime on CentOS 8

### ISSUE THREAD

**Issue by tedgin** [irods/irods_client_icommands#320] opened 2022-09-13 21:00 UTC
I was able to install version 4.3.0 of iCommands on a CentOS 8 machine by following the instructions on https://packages.irods.org and doing `yum install irods-icommands`.  Unfortunately, the dependency `irods-runtime` wasn't automatically installed, and I had to install it with a second yum call, `yum install irods-runtime`.

**Comment by alanking** [comment] 2022-09-13 21:02
I believe this is a duplicate of https://github.com/irods/irods/issues/6564

**Comment by trel** [comment] 2022-09-13 22:24
Ah, it did sound vaguely familiar.   Yes, duplicate!

**Closed** 2022-09-13 22:24 UTC
